# Permalinks
permalink:        pretty

# Setup
url:              http://muchuanyun.github.io

# Set to '' in case of hosting on `http://<your-github-name>.github.io`
baseurl:         '/mu_zone' 

title:           Code_Poem 

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:      >
  As a Chinese traditional poetry lover, I have to say, code is just like poetry. 

# The tags listed as entries in the sidebar
sidebar_tags:     [jekyll, hyde]

# Fallback image and color if not overwritten for tag or post
image:            /mu_zone/public/img/nap.jpg
color:            '#A85641'

author:
  name:           'Yaping Sun'

  # Setting social media usernames will add icons at the bottom of the sidebar
  twitter:        vimko
  github:         muchuanyun 

  # Setting a disqus username will enable the comment section
  # disqus:         qwtel

  # This photo will be used in the about section
  photo:         http://muchuanyun.github.io/muzone/public/img/kitten.jpg

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:          |
    Hi, I'm Yaping Sun. 

kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: true
